# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template enums.py.jinja --
from ._compat import StrEnum


class event_type(StrEnum):
    RENDEZ_VOUS = 'RENDEZ_VOUS'
    OPERATION = 'OPERATION'
    AUTRE = 'AUTRE'

class genders(StrEnum):
    M = 'M'
    F = 'F'
    N_A = 'N_A'

class payment(StrEnum):
    PAYER = 'PAYER'
    A_PAYER = 'A_PAYER'
    EN_COURS_DE_PAIEMENT = 'EN_COURS_DE_PAIEMENT'
    NON_PAYER = 'NON_PAYER'

class roles(StrEnum):
    DIRECTEUR = 'DIRECTEUR'
    VETERINAIRE = 'VETERINAIRE'
    ASSISTANT = 'ASSISTANT'

class statuses(StrEnum):
    ACTIF = 'ACTIF'
    INACTIF = 'INACTIF'

class statuts(StrEnum):
    A_FAIRE = 'A_FAIRE'
    REPORTER = 'REPORTER'
    ANNULER = 'ANNULER'
    TERMINER = 'TERMINER'

