from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'allergies',
    'booster_shots',
    'clients',
    'earnings',
    'events',
    'expenses',
    'invoices',
    'items_bought',
    'items_sold',
    'patients',
    'patients_allergies',
    'prescriptions',
    'product_types',
    'products',
    'users',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'allergies': {
        'patients_allergies': 'patients_allergies',
    },
    'booster_shots': {
        'patients': 'patients',
    },
    'clients': {
        'earnings': 'earnings',
        'events': 'events',
        'invoices': 'invoices',
        'patients': 'patients',
    },
    'earnings': {
        'clients': 'clients',
        'invoices': 'invoices',
        'items_sold': 'items_sold',
    },
    'events': {
        'clients': 'clients',
        'patients': 'patients',
        'users': 'users',
    },
    'expenses': {
        'items_bought': 'items_bought',
    },
    'invoices': {
        'clients': 'clients',
        'earnings': 'earnings',
    },
    'items_bought': {
        'expense': 'expenses',
        'product': 'products',
    },
    'items_sold': {
        'earning': 'earnings',
        'product': 'products',
    },
    'patients': {
        'booster_shots': 'booster_shots',
        'events': 'events',
        'clients': 'clients',
        'patients_allergies': 'patients_allergies',
        'prescriptions': 'prescriptions',
    },
    'patients_allergies': {
        'allergies': 'allergies',
        'patients': 'patients',
    },
    'prescriptions': {
        'patients': 'patients',
    },
    'product_types': {
        'products': 'products',
    },
    'products': {
        'product_types': 'product_types',
        'items_bought': 'items_bought',
        'items_sold': 'items_sold',
    },
    'users': {
        'events': 'events',
    },
}

# fmt: on